### ISSUE TITLE
[New Team]: no(low)-code tools for DAO,NFT,AI (ERC4337)

### ISSUE THREAD

**Issue by yujiym** [ethereumjp/find-hackathon-team#11]
## Introduction
- a full-stack dev in tokyo (prefer frontend dev and UX).
- been involved in web3 for about 4 years, mainly DeFi project.
- have attended ethglobal hackathons several times and got some prizes.
- I would like to try a passkey idea, but I would like to join any other team that has a good idea.

## Idea description
- set up app web3 functionality (dify.ai like UI) and publish app link
- create accounts with passkey (smartwallet.dev or safe or other AA)
- add web3 functionality to existing apps and groups via app link

## Skillset
- interested in this area and would like to discuss ideas.

- [ ] Core Blockchain Development (Go, Rust, C++)
- [x] Smart Contracts (Solidity, Vyper)
- [x] dApps (JavaScript, webdev)
- [ ] Blockchain Operations, Infrastructure
- [ ] Game theory, Crypto-Economics
- [ ] Design, User Experience
- [ ] Project Management
- [ ] _Other_: ...

## Communication
- telegram: `yujiym`
- twitter: `@yujiym`

**Comment by lamtrinh259** [comment]
@yujiym messaged you on Telegram
