### ISSUE TITLE
[Looking for team]: Smart Contract Developer - Rust, Security

### ISSUE THREAD

**Issue by encody** [ethereumjp/find-hackathon-team#3]
## Background

I've been working full-time in Web3 since 2021, and have been involved in crypto generally since 2017.

Currently a graduate student in mathematics and computing science at Tokyo Tech. Occasionally write mostly technical posts on [my website](https://geeklaunch.io), and videos on [my YouTube channel](https://youtube.com/GeekLaunch).

## Skills

7 years Rust experience, Secureum (auditing) certified in Solidity smart contract development. Also comfortable with backend/applications development, and have a decent amount of experience with frontend.

- [x] Core Blockchain Development in Rust.
- [x] Smart Contracts in Solidity, Rust, Move.
- [x] Frontend. Worked professionally with all of React, Angular, and Vue.
- [x] Auditing Solidity and NEAR Rust contracts.

## Communication

- [Session](https://getsession.org/): `05b49d75f0a7165bac49126872f89766dfa53ab51fd0832de8bbb71458b348cc08`
- [Twitter: `sudo_build`](https://twitter.com/sudo_build)
- Web3 should stop using Telegram. If you insist: `encody`.

**Comment by laciferin2024** [comment]
Hi, Lets connect: 

Linkedin: https://linkedin.com/in/laciferin

X: https://x.com/laciferin


I gotta say: u do venture into least explored realms of knowledge. I m building an offline zk based payment system, if u r interested let me know.

**Comment by lamtrinh259** [comment]
@encody hello, we should definitely connect. Would love to see if we can collaborate together. I have sent you a message on Telegram.
