### ISSUE TITLE
[Looking for team]: Fullstack + Solidity dev

### ISSUE THREAD

**Issue by grandsmarquis** [ethereumjp/find-hackathon-team#6]
## Background

I'm a fullstack dev working full time in the Ethereum universe since 2017. I worked on games, dev tools, NFT exchanges... I'm looking for a team. I didn't participate to a hackathon since long time but I'm good at designing and shipping products super fast.
I'm fast learner and can adapt to any technologies. I speak English, French and a little bit of Japanese.

I'm pretty interested in all fields and wold love to experiment more in the field of privacy, ownership and gaming.

## Skills

- [x] Smart Contracts (Solidity)
- [x] dApps (JavaScript, webdev, React, NextJS, Postgres)
- [x] Blockchain Operations, Infrastructure
- [x] Design, User Experience
- [x] Blockchain Data ingestion
- [x] Blockchain Data analytics

## Communication

You can contact me here or on Telegram [@grands_marquis](https://t.me/grands_marquis) or twitter [@grands_marquis](https://x.com/grands_marquis).

**Comment by lamtrinh259** [comment]
@grandsmarquis hi, I contacted you on Telegram, let's chat there.
