### ISSUE TITLE
[Hacker wanted]: Looking for a member

### ISSUE THREAD

**Issue by ryptoc** [ethereumjp/find-hackathon-team#8]
## Pitch it!

I'm co-founder of a blockchain dev company and a backend and smart contract developer who has built and designed a few  DeFi and other protocols from scratch. I love ideas and building them.
My friend is a founder of a project and also very knowledgeable in the blockchain space with awesome presentation skills and lots of ideas. 

We've come up with some concepts around decentralized reputation. Generally, we're very open to new ideas and suggestions as well.

~~As there can be only 4 team members, we for sure need at least one FE developer. Ideally, this person also knows some design, or we can also take one UX/UI designer on board.~~

_Update: we've found one member who does FE and Figma._

Now we're searching for one more team member.

Send me a DM on Telegram, and we can quickly sync up on the idea and other details. 

## Communication

- [x] _telegram_: `@dan_ryptoc`

**Comment by Kyoya67** [comment]
I sent DM. Please see it. Thank you!!!
